# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `letter_opener_web` gem.
# Please instead update this file by running `bin/tapioca gem letter_opener_web`.


# source://letter_opener_web//lib/letter_opener_web/version.rb#3
module LetterOpenerWeb
  class << self
    # source://letter_opener_web//lib/letter_opener_web.rb#12
    def config; end

    # @yield [config]
    #
    # source://letter_opener_web//lib/letter_opener_web.rb#18
    def configure; end

    # source://railties/8.0.2/lib/rails/engine.rb#413
    def railtie_helpers_paths; end

    # source://railties/8.0.2/lib/rails/engine.rb#396
    def railtie_namespace; end

    # source://railties/8.0.2/lib/rails/engine.rb#417
    def railtie_routes_url_helpers(include_path_helpers = T.unsafe(nil)); end

    # source://letter_opener_web//lib/letter_opener_web.rb#22
    def reset!; end

    # source://railties/8.0.2/lib/rails/engine.rb#402
    def table_name_prefix; end

    # source://railties/8.0.2/lib/rails/engine.rb#409
    def use_relative_model_naming?; end
  end
end

class LetterOpenerWeb::ApplicationController < ::ActionController::Base
  private

  # source://actionview/8.0.2/lib/action_view/layouts.rb#328
  def _layout(lookup_context, formats, keys); end

  class << self
    private

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr___callbacks; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr___callbacks=(new_value); end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr_middleware_stack; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr_middleware_stack=(new_value); end
  end
end

# source://letter_opener_web//lib/letter_opener_web.rb#8
class LetterOpenerWeb::Config
  # Returns the value of attribute letters_location.
  #
  # source://letter_opener_web//lib/letter_opener_web.rb#9
  def letters_location; end

  # Sets the attribute letters_location
  #
  # @param value the value to set the attribute letters_location to.
  #
  # source://letter_opener_web//lib/letter_opener_web.rb#9
  def letters_location=(_arg0); end
end

# source://letter_opener_web//lib/letter_opener_web/delivery_method.rb#6
class LetterOpenerWeb::DeliveryMethod < ::LetterOpener::DeliveryMethod
  # source://letter_opener_web//lib/letter_opener_web/delivery_method.rb#7
  def deliver!(mail); end
end

# source://letter_opener_web//lib/letter_opener_web/engine.rb#7
class LetterOpenerWeb::Engine < ::Rails::Engine
  class << self
    private

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr___callbacks; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr___callbacks=(new_value); end
  end
end

class LetterOpenerWeb::Letter
  def initialize(params); end

  def attachments; end
  def default_style; end
  def delete; end
  def headers; end
  def id; end
  def plain_text; end
  def rich_text; end
  def sent_at; end
  def to_param; end
  def valid?; end

  private

  def adjust_link_targets(contents); end
  def base_dir; end
  def base_dir_within_letters_location?; end
  def exists?; end
  def fix_link_html(link_html); end
  def read_file(style); end
  def remove_attachments_link(headers); end
  def style_exists?(style); end

  class << self
    def destroy_all; end
    def find(id); end
    def letters_location; end
    def letters_location=(directory); end
    def search; end
  end
end

class LetterOpenerWeb::LettersController < ::LetterOpenerWeb::ApplicationController
  def attachment; end
  def clear; end
  def destroy; end
  def index; end
  def show; end

  private

  # source://actionview/8.0.2/lib/action_view/layouts.rb#328
  def _layout(lookup_context, formats, keys); end

  def check_style; end
  def load_letter; end
  def routes; end

  class << self
    private

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr___callbacks; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr___callbacks=(new_value); end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr_middleware_stack; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr_middleware_stack=(new_value); end
  end
end

# source://letter_opener_web//lib/letter_opener_web/version.rb#4
LetterOpenerWeb::VERSION = T.let(T.unsafe(nil), String)
